Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FisioTerapias.Models;

namespace FisioTerapias.Controllers
{
    public class RolesController : Controller
    {
        private readonly RehabilitacionContext _context;

        public RolesController(RehabilitacionContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.IdRol == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRol,Descripcion")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRol,Descripcion")] Role role)
        {
            if (id != role.IdRol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.IdRol))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.IdRol == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.IdRol == id);
        }
    }
}

Controllers/TerapiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FisioTerapias.Models;

namespace FisioTerapias.Controllers
{
    public class TerapiasController : Controller
    {
        private readonly RehabilitacionContext _context;

        public TerapiasController(RehabilitacionContext context)
        {
            _context = context;
        }

        // GET: Terapias
        public async Task<IActionResult> Index()
        {
            var rehabilitacionContext = _context.Terapias.Include(t => t.IdEmpleadoNavigation).Include(t => t.IdEstadoTerapiaNavigation).Include(t => t.IdPacienteNavigation);
            return View(await rehabilitacionContext.ToListAsync());
        }

        // GET: Terapias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terapia = await _context.Terapias
                .Include(t => t.IdEmpleadoNavigation)
                .Include(t => t.IdEstadoTerapiaNavigation)
                .Include(t => t.IdPacienteNavigation)
                .FirstOrDefaultAsync(m => m.IdTerapia == id);
            if (terapia == null)
            {
                return NotFound();
            }

            return View(terapia);
        }

        // GET: Terapias/Create
        public IActionResult Create()
        {
            ViewBag.IdEmpleado = _context.Empleados;
            ViewBag.IdEstadoTerapia = _context.EstadoTerapias;
            ViewBag.IdPaciente = _context.Pacientes;

            ViewBag.IdEstadoPaciente = _context.EstadoPacientes;
            ViewBag.IdTerapia = _context.Terapias;
            return View();
        }

        // POST: Terapias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            DateTime Fecha,
            string Diagnostico,
            string NecesidadDelPaciente,
            int IdPaciente,
            int IdEstadoTerapia,
            int IdEmpleado,
            string Sensacion,
            string Observaciones,
            int Dolor,
            int IdEstadoPaciente
            )
        {
            
            //if (ModelState.IsValid)
            //{
            //    _context.Add(terapia);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}


            ViewBag.IdEmpleado = _context.Empleados;
            ViewBag.IdEstadoTerapia = _context.EstadoTerapias;
            ViewBag.IdPaciente = _context.Pacientes;

            return View();
        }

        //// GET: Terapias/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var terapia = await _context.Terapias.FindAsync(id);
        //    if (terapia == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", terapia.IdEmpleado);
        //    ViewData["IdEstadoTerapia"] = new SelectList(_context.EstadoTerapias, "IdEstadoTerapia", "IdEstadoTerapia", terapia.IdEstadoTerapia);
        //    ViewData["IdPaciente"] = new SelectList(_context.Pacientes, "IdPaciente", "IdPaciente", terapia.IdPaciente);
        //    return View(terapia);
        //}

        //// POST: Terapias/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("IdTerapia,Fecha,Diagnostico,Historial,NecesidadDelPaciente,CantidadDeTerapias,IdPaciente,IdEstadoTerapia,IdEmpleado")] Terapia terapia)
        //{
        //    if (id != terapia.IdTerapia)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(terapia);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!TerapiaExists(terapia.IdTerapia))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", terapia.IdEmpleado);
        //    ViewData["IdEstadoTerapia"] = new SelectList(_context.EstadoTerapias, "IdEstadoTerapia", "IdEstadoTerapia", terapia.IdEstadoTerapia);
        //    ViewData["IdPaciente"] = new SelectList(_context.Pacientes, "IdPaciente", "IdPaciente", terapia.IdPaciente);
        //    return View(terapia);
        //}

        // GET: Terapias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terapia = await _context.Terapias
                .Include(t => t.IdEmpleadoNavigation)
                .Include(t => t.IdEstadoTerapiaNavigation)
                .Include(t => t.IdPacienteNavigation)
                .FirstOrDefaultAsync(m => m.IdTerapia == id);
            if (terapia == null)
            {
                return NotFound();
            }

            return View(terapia);
        }

        // POST: Terapias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var terapia = await _context.Terapias.FindAsync(id);
            if (terapia != null)
            {
                _context.Terapias.Remove(terapia);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TerapiaExists(int id)
        {
            return _context.Terapias.Any(e => e.IdTerapia == id);
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FisioTerapias.Models;

namespace FisioTerapias.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly RehabilitacionContext _context;

        public UsuariosController(RehabilitacionContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            var rehabilitacionContext = _context.Usuarios.Include(u => u.IdEmpleadoNavigation).Include(u => u.IdRolNavigation);
            return View(await rehabilitacionContext.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.IdEmpleadoNavigation)
                .Include(u => u.IdRolNavigation)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado");
            ViewData["IdRol"] = new SelectList(_context.Roles, "IdRol", "IdRol");
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuario,Usuario1,Clave,Correo,IdEmpleado,IdRol")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", usuario.IdEmpleado);
            ViewData["IdRol"] = new SelectList(_context.Roles, "IdRol", "IdRol", usuario.IdRol);
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", usuario.IdEmpleado);
            ViewData["IdRol"] = new SelectList(_context.Roles, "IdRol", "IdRol", usuario.IdRol);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,Usuario1,Clave,Correo,IdEmpleado,IdRol")] Usuario usuario)
        {
            if (id != usuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", usuario.IdEmpleado);
            ViewData["IdRol"] = new SelectList(_context.Roles, "IdRol", "IdRol", usuario.IdRol);
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.IdEmpleadoNavigation)
                .Include(u => u.IdRolNavigation)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.IdUsuario == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FisioTerapias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FisioTerapias.styles.css" asp-append-version="true" />

    <!-- Google Fonts: Roboto -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <style>
        body {
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FisioTerapias</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- Pacientes y Especialistas -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="pacientesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Pacientes
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="pacientesDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Terapias" asp-action="Index">Lista de Terapias</a></li>
                                @* <li><a class="dropdown-item" asp-area="" asp-controller="Seguimientoes" asp-action="Index">Lista de Seguimientos</a></li> *@
                            </ul>
                        </li>

                        <!-- Mantenimiento -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="mantenimientoDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Mantenimiento
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="mantenimientoDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Pacientes" asp-action="Index">Lista de Pacientes</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Empleadoes" asp-action="Index">Lista de Especialistas</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="EstadoPacientes" asp-action="Index">Lista de Estados Pacientes</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Lista de Roles</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="EstadoTerapias" asp-action="Index">Lista de Estados Terapias</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Usuarios" asp-action="Index">Lista de Usuarios</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Especialidades" asp-action="Index">Lista de Especialidades</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FisioTerapias - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>